---QUERY FOR SQL-CHALLENGE
--- FOR EMPLOYEE DETAILS
select E."EMP_NO",E."LAST_NAME",E."SEX",S."SALARY" FROM "EMPLOYEE" AS E, "SALARY" AS S
WHERE S."EMP_NO" = E."EMP_NO"

---DISPLAY EMPLOYEE INFO HIRED IN 1986
SELECT "FIRST_NAME","LAST_NAME","HIRE_DATE" FROM "EMPLOYEE"
WHERE "HIRE_DATE" BETWEEN '1986-01-01' AND '1986-12-31'

--SHOW MANAGER INFO
SELECT DM."DEPT_NO", D."DEPT_NAME", DM."EMP_NO", E."LAST_NAME", E."FIRST_NAME"  FROM "DEPT_MANAGER" AS DM, "DEPARTMENT" AS D, "EMPLOYEE" AS E
WHERE DM."DEPT_NO"=D."DEPT_NO" AND DM."EMP_NO"=E."EMP_NO"

--List the department of each employee with the following information:
---employee number, last name, first name, and department name.
SELECT E."EMP_NO", E."LAST_NAME", E."FIRST_NAME", D."DEPT_NAME" FROM "EMPLOYEE" AS E, "DEPT_EMP" AS DE, "DEPARTMENT" AS D
WHERE E."EMP_NO"=DE."EMP_NO" AND DE."DEPT_NO"=D."DEPT_NO"
---(5)
SELECT "FIRST_NAME", "LAST_NAME", "SEX" FROM "EMPLOYEE"
WHERE "FIRST_NAME" = 'Hercules' AND "LAST_NAME" LIKE 'B%'

----(6)
SELECT E."EMP_NO", E."LAST_NAME", E."FIRST_NAME", D."DEPT_NAME" FROM "EMPLOYEE" AS E, "DEPT_EMP" AS DE, "DEPARTMENT" AS D
WHERE E."EMP_NO"=DE."EMP_NO" AND DE."DEPT_NO"=D."DEPT_NO" AND D."DEPT_NAME" = 'Sales'


---(7)
SELECT E."EMP_NO", E."LAST_NAME", E."FIRST_NAME", D."DEPT_NAME" 
FROM "EMPLOYEE" AS E, "DEPT_EMP" AS DE, "DEPARTMENT" AS D
WHERE E."EMP_NO"=DE."EMP_NO" AND DE."DEPT_NO"=D."DEPT_NO" AND D."DEPT_NAME" IN ('Sales', 'Development')
---(8)
SELECT "LAST_NAME", COUNT("LAST_NAME") AS "NAME_COUNT"
FROM "EMPLOYEE"
GROUP BY "LAST_NAME"
ORDER BY "NAME_COUNT" DESC;




