
DROP table if exists "DEPARTMENT";
DROP table if exists "DEPT_EMP";
DROP table if exists"DEPT_MANAGER";
DROP table if exists "EMPLOYEE";
DROP table if exists"SALARY";
DROP table if exists "TITLE";

CREATE TABLE "DEPARTMENT" (
    "DEPT_NO" varchar(10)   NOT NULL,
    "DEPT_NAME" varchar(100)   NOT NULL,
    CONSTRAINT "pk_DEPARTMENT" PRIMARY KEY ("DEPT_NO")
);

CREATE TABLE "DEPT_EMP" (
    "EMP_NO" int   NOT NULL,
    "DEPT_NO" varchar(10)   NOT NULL
);

CREATE TABLE "DEPT_MANAGER" (
    "DEPT_NO" varchar(10)   NOT NULL,
    "EMP_NO" int   NOT NULL
);

CREATE TABLE "EMPLOYEE" (
    "EMP_NO" int   NOT NULL,
    "EMP_TITLE_ID" varchar(10)   NOT NULL,
    "BIRTH_DATE" date   NOT NULL,
    "FIRST_NAME" varchar(100)   NOT NULL,
    "LAST_NAME" varchar(100)   NOT NULL,
    "SEX" varchar(1)   NOT NULL,
    "HIRE_DATE" date   NOT NULL,
    CONSTRAINT "pk_EMPLOYEE" PRIMARY KEY (
        "EMP_NO"
     )
);

CREATE TABLE "SALARY" (
    "EMP_NO" int   NOT NULL,
    "SALARY" int   NOT NULL
);

CREATE TABLE "TITLE" (
    "TITLE_ID" varchar(10)   NOT NULL,
    "TITLE" varchar(100)   NOT NULL
);

ALTER TABLE "DEPT_EMP" ADD CONSTRAINT "fk_DEPT_EMP_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEE" ("EMP_NO");

ALTER TABLE "DEPT_EMP" ADD CONSTRAINT "fk_DEPT_EMP_DEPT_NO" FOREIGN KEY("DEPT_NO")
REFERENCES "DEPARTMENT" ("DEPT_NO");

ALTER TABLE "DEPT_MANAGER" ADD CONSTRAINT "fk_DEPT_MANAGER_DEPT_NO" FOREIGN KEY("DEPT_NO")
REFERENCES "DEPARTMENT" ("DEPT_NO");

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "fk_EMPLOYEE_EMP_TITLE_ID" FOREIGN KEY("EMP_TITLE_ID")
REFERENCES "TITLE" ("TITLE_ID");

ALTER TABLE "SALARY" ADD CONSTRAINT "fk_SALARY_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEE" ("EMP_NO");

ALTER TABLE "TITLE" ADD CONSTRAINT "fk_TITLES_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEE" ("EMP_NO");

select * from "DEPARTMENT"
select * from "DEPT_EMP"
select * from "DEPT_MANAGER"
SELECT * FROM "EMPLOYEE"
SELECT * FROM "SALARY"
SELECT * FROM "TITLE"



